#pragma once

/* pmw3610用定義 */

#define PMW3610_CS_PIN NO_PIN
#define PMW3610_MOTION_PIN GP3
#define PMW3610_SCLK_PIN GP2
#define PMW3610_SDIO_PIN GP0

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT

#define DEBUG_PRINT