#pragma once

#define PMW33XX_CS_PIN GP5
#define SPI_SCK_PIN GP2
#define SPI_MISO_PIN GP4
#define SPI_MOSI_PIN GP3

#define I2C1_SCL_PIN GP19
#define I2C1_SDA_PIN GP18
#define I2C_DRIVER I2CD1

#define MOUSE_FIXED_THETA (90)
#define MOUSE_FIXED_PHY (180)
#define MOUSE_FIXED_SCRDIV (60)
#define MOUSE_FIXED_INVERT_X (false)
#define MOUSE_FIXED_SCROLL_LAYER (3)
#define MOUSE_FIXED_ORTH_SCROLL (false)