#pragma once

// StickPoint

#define PIMORONI_TRACKBALL_ADDRESS 0x0A
#define F_SCL 100000
#define PIMORONI_TRACKBALL_SCALE 8

#define MOUSE_FIXED_INVERT_X (false)
#define MOUSE_FIXED_THETA (270)
#define MOUSE_FIXED_PHY (180)