#pragma once

/* RKD07SPに共通の機能*/

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_DRIVER SIOD0

#define I2C1_SCL_PIN GP19
#define I2C1_SDA_PIN GP18
#define I2C_DRIVER I2CD1

#define MOUSE_FIXED_SCROLL_LAYER (3)
#define MOUSE_FIXED_ORTH_SCROLL (false)

#define RKD_USE_DEFAULT_CUSTOM_KEYS
#define RKD_USE_DEFAULT_CUSTOM_MOUSE

#define RKE_OLED_ROTATIN OLED_ROTATION_180
#define RKD_USE_DEFAULT_OLED
