#pragma once

#define SERIAL_USART_TX_PIN GP16
#define SERIAL_USART_RX_PIN GP17

#define MOUSE_FIXED_THETA (270)
#define MOUSE_FIXED_PHY (0)
#define MOUSE_FIXED_SCRDIV (60)
#define MOUSE_FIXED_INVERT_X (true)